### ISSUE TITLE
Social Liberals and Market Liberals

### ISSUE THREAD

**Issue by ArchibaldSinclair** [TitaniumRogue/ideologies#46]
The Canadian Liberal Party at the time was more Market than Social Liberal.

**Comment by PapaMeme** [comment]
Hi, I made the parties for Canada. I made the Libs have the Social Liberal faction be the ruling faction because after the great depression and the collapse of Bennett, Mackenzie King, leader of the liberal party, undertook a sort of ideological transformation. Now whether this change towards intervention in the market was due to political opportunism or not, who knows. But it was a definite rejection of moderate and market forces in the liberal party, with Mackenzie King embracing Rooseveltian and Keynesian ideals, thus making it impossible for me to make him a market lib. 

Instead the market libs represent, anti-"new deal" type policy liberals.
